[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fintech_langgraph"
version = "0.1.0"
description = "A multi-agent system for financial advice using LangChain and OpenAI's GPT models"
requires-python = ">=3.8" 